export const CONSTANTS = {
  BASE_INPUT_TYPE: {
    TEXT: "text",
    TEXTAREA: "textarea",
    TIME_PICKER: "time-picker",
    FLOAT_NUM: "float-num",
    CHECKBOX: "checkbox",
    DATE: "date",
    COMBOBOX: "combobox",
  },
  COLUMN_NAME_SHIFT: {
    ShiftId: "shiftId",
    ShiftCode: "shiftCode",
    ShiftName: "shiftName",
    ShiftDescription: "shiftDescription",
    ShiftBeginTime: "shiftBeginTime",
    ShiftEndTime: "shiftEndTime",
    ShiftBeginBreakTime: "shiftBeginBreakTime",
    ShiftEndBreakTime: "shiftEndBreakTime",
    ShiftWorkingTime: "shiftWorkingTime",
    ShiftBreakingTime: "shiftBreakingTime",
    ShiftStatus: "shiftStatus",
    CreatedBy: "createdBy",
    CreatedDate: "createdDate",
    ModifiedBy: "modifiedBy",
    ModifiedDate: "modifiedDate",
  },
  COLUMN_NAME_SHIFT_FILTER: {
    shiftCode: "shift_code",
    shiftName: "shift_name",
    shiftDescription: "shift_description",
    shiftBeginTime: "shift_begin_time",
    shiftEndTime: "shift_end_time",
    shiftBeginBreakTime: "shift_begin_break_time",
    shiftEndBreakTime: "shift_end_break_time",
    shiftWorkingTime: "shift_working_time",
    shiftBreakingTime: "shift_breaking_time",
    shiftStatus: "shift_status",
    createdBy: "created_by",
    createdDate: "created_date",
    modifiedBy: "modified_by",
    modifiedDate: "modified_date",
  },
  ERROR_RESPONSE: {
    FieldName: "FieldName",
    ErrorMessage: "ErrorMessage",
  },
  FILTER_COLUMN_TYPE_TEXT: {
    0: "Khác",
    1: "Chứa",
    2: "Không chứa",
    3: "Bắt đầu với",
    4: "Kết thúc với",
  },
  DATE_FILTER_COLUMN_TYPE_TEXT: {
    0: "Bằng",
    1: "Khác",
    2: "Nhỏ hơn",
    3: "Nhỏ hơn hoặc bằng",
    4: "Lớn hơn",
    5: "Lớn hơn hoặc bằng",
    6: "(Trống)",
    7: "(Không trống)",
  },
  STATUS_SHIFT: {
    1: "Đang sử dụng",
    0: "Ngừng sử dụng",
    Active: 1,
    Inactive: 0,
  },
  FilterColumnType: {
    Difference: 0,
    Contains: 1,
    NotContains: 2,
    StartsWith: 3,
    EndsWith: 4,
  },
  DateFilterColumnType: {
    Equal: 0,
    Different: 1,
    Less: 2,
    LessOrEqual: 3,
    Greater: 4,
    GreaterOrEqual: 5,
    Empty: 6,
    NotEmpty: 7,
  },
  SORT_TYPE: {
    Descending: 0,
    Ascending: 1,
    Default: 2,
  },
  FilterOptionsType: {
    Text: [
      { text: "Khác", value: 0, isSelected: true },
      {
        text: "Chứa",
        value: 1,
        isSelected: false,
      },
      {
        text: "Không chứa",
        value: 2,
        isSelected: false,
      },
      {
        text: "Bắt đầu với",
        value: 3,
        isSelected: false,
      },
      {
        text: "Kết thúc với",
        value: 4,
        isSelected: false,
      },
    ],
    Date: [
      { text: "Bằng", value: 0, isSelected: false },
      {
        text: "Khác",
        value: 1,
        isSelected: true,
      },
      {
        text: "Nhỏ hơn",
        value: 2,
        isSelected: false,
      },
      {
        text: "Nhỏ hơn hoặc bằng",
        value: 3,
        isSelected: false,
      },
      {
        text: "Lớn hơn",
        value: 4,
        isSelected: false,
      },
      {
        text: "Lớn hơn hoặc bằng",
        value: 5,
        isSelected: false,
      },
      {
        text: "(Trống)",
        value: 6,
        isSelected: false,
      },
      {
        text: "(Không trống)",
        value: 7,
        isSelected: false,
      },
    ],
  },
};
