export const CONSTANTS = {
  BASE_INPUT_TYPE: {
    TEXT: 'text',
    TEXTAREA: 'textarea',
    TIME_PICKER: 'time-picker',
    FLOAT_NUM: 'float-num',
    CHECKBOX: 'checkbox',
    DATE: 'date',
    COMBOBOX: 'combobox',
  },
  STATUS_SHIFT: {
    1: "Đang sử dụng",
    0: "Ngừng sử dụng",
    Active: 1,
    Inactive: 0,
  },
  COLUMN_NAME_SHIFT: {
    ShiftId: 'shiftId',
    ShiftCode: 'shiftCode',
    ShiftName: 'shiftName',
    ShiftDescription: 'shiftDescription',
    ShiftBeginTime: 'shiftBeginTime',
    ShiftEndTime: 'shiftEndTime',
    ShiftBeginBreakTime: 'shiftBeginBreakTime',
    ShiftEndBreakTime: 'shiftEndBreakTime',
    ShiftWorkingTime: 'shiftWorkingTime',
    ShiftBreakingTime: 'shiftBreakingTime',
    ShiftStatus: 'shiftStatus',
    CreatedBy: 'createdBy',
    CreatedDate: 'createdDate',
    ModifiedBy: 'modifiedBy',
    ModifiedDate: 'modifiedDate',
  },
  COLUMN_NAME_SHIFT_FILTER: {
    ShiftCode: 'shift_code',
    ShiftName: 'shift_name',
    ShiftDescription: 'shift_description',
    ShiftBeginTime: 'shift_begin_time',
    ShiftEndTime: 'shift_end_time',
    ShiftBeginBreakTime: 'shift_begin_break_time',
    ShiftEndBreakTime: 'shift_end_break_time',
    ShiftWorkingTime: 'shift_working_time',
    ShiftBreakingTime: 'shift_breaking_time',
    ShiftStatus: 'shift_status',
    CreatedBy: 'created_by',
    CreatedDate: 'created_date',
    ModifiedBy: 'modified_by',
    ModifiedDate: 'modified_date',
  },
  ERROR_RESPONSE: {
    FieldName: 'FieldName',
    ErrorMessage: 'ErrorMessage',
  },
  FILTER_COLUMN_TYPE_TEXT: {
    0: "Khác",
    1: "Chứa",
    2: "Không chứa",
    3: "Bắt đầu với",
    4: "Kết thúc với",
  },
  DATE_FILTER_COLUMN_TYPE_TEXT: {
    0: "Bằng",
    1: "Khác",
    2: "Nhỏ hơn",
    3: "Nhỏ hơn hoặc bằng",
    4: "Lớn hơn",
    5: "Lớn hơn hoặc bằng",
    6: "(Trống)",
    7: "(Không trống)",
  },
}

export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || 'https://localhost:7284',
  TIMEOUT: 30000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000,
};
